<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-SAPACB4E" failures="2" tests="2" name="Test" time="0.731" errors="0" timestamp="2022-11-23T18:24:20 IST">
  <testcase classname="com.facebook.com.facebook.ReadExcel" name="data" time="0.011">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.facebook.com.facebook.ReadExcel.data(ReadExcel.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- data -->
  <testcase classname="com.facebook.com.facebook.ReadExcel" name="readDataFromExcel" time="0.536">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;java.lang.CharSequence.length()&amp;quot; because &amp;quot;this.text&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1770)
at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
at java.base/java.util.regex.Matcher.<init>(Matcher.java:253)
at java.base/java.util.regex.Pattern.matcher(Pattern.java:1134)
at com.relevantcodes.extentreports.utils.ExceptionUtil.getExceptionHeadline(ExceptionUtil.java:25)
at com.relevantcodes.extentreports.utils.ExceptionUtil.createExceptionInfo(ExceptionUtil.java:34)
at com.relevantcodes.extentreports.ExtentTest.log(ExtentTest.java:131)
at com.relevantcodes.extentreports.ExtentTest.log(ExtentTest.java:164)
at com.facebook.com.facebook.TestListner.onTestSuccess(TestListner.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- readDataFromExcel -->
</testsuite> <!-- Test -->
